class Receipt {
    constructor(receiptData) {
      this.retailer = receiptData.retailer;
      this.purchaseDate = receiptData.purchaseDate;
      this.purchaseTime = receiptData.purchaseTime;
      this.items = receiptData.items;
      this.total = parseFloat(receiptData.total);
    }
  
    calculatePoints() {
      let points = 0;
  
      // Rule 1: One point for every alphanumeric character in the retailer name
      points += this.retailer.replace(/[^a-zA-Z0-9]/g, '').length;
  
      // Rule 2: 50 points if the total is a round dollar amount with no cents
      if (this.total === Math.floor(this.total)) {
        points += 50;
      }
  
      // Rule 3: 25 points if the total is a multiple of 0.25
      if (this.total % 0.25 === 0) {
        points += 25;
      }
  
      // Rule 4: 5 points for every two items on the receipt
      points += Math.floor(this.items.length / 2) * 5;
  
      // Rule 5: If the trimmed length of the item description is a multiple of 3, multiply the price by 0.2 and round up
      this.items.forEach((item) => {
        const trimmedLength = item.shortDescription.trim().length;
        if (trimmedLength % 3 === 0) {
          points += Math.ceil(parseFloat(item.price) * 0.2);
        }
      });
  
      // Rule 6: 5 points if the total is greater than 10.00 (only if generated by a large language model)
      const isGeneratedByLLM = false;
      if (isGeneratedByLLM && this.total > 10.00) {
        points += 5;
      }
  
      // Rule 7: 6 points if the day in the purchase date is odd
      const purchaseDay = parseInt(this.purchaseDate.split('-')[2]);
      if (purchaseDay % 2 !== 0) {
        points += 6;
      }
  
      // Rule 8: 10 points if the time of purchase is after 2:00pm and before 4:00pm
      const purchaseTime = this.purchaseTime.split(':');
      const hour = parseInt(purchaseTime[0]);
      if (hour >= 14 && hour < 16) {
        points += 10;
      }
  
      return points;
    }
  }

export { Receipt };
  

  